version: '3.8'
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  user-service:
    image: aiirakesh/user:latest
    pull_policy: always
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  mongodb_data:
