apiVersion: apps/v1
kind: Deployment # Kind of Kubernetes file

# Define metadata of deployment file
metadata:
  name: gateway-deployment
  labels:
    app: gateway

# Specifications of deployment file
spec:
  replicas: 1 # How many replicas are we trying to create.
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    
    # Specification of image. Docker image information
    spec:
      containers:
      - name: gateway
        image: aiirakesh/gateway:latest  # Url of docker registry of gateway
        ports:
        - containerPort: 3000
        env:
          - name: MONGODB_HOST
            value: "user-service.default:8000"  # This is provided like this formate <nameOfService>.<namespace>:<port>