apiVersion: v1
# Kind of Kubernetes file
kind: Service

# Metadata of service file
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  ports:
    - protocol:
      port: 8001
      targetPort: 3000
  selector:
    app: gateway
